SERVER:
  ADDRESS: 127.0.0.1
  PORT: 8000
  URL_PREFIX: http://localhost:8000 # 地址前缀，不以/结尾
  SECRET_KEYS: 'this is secret key' # 加密session用的key
  MAXAGE: 0 # 静态资源缓存时间,单位ms,推荐在正式服务器上启用

MONGODB: # mongodb配置DEV
  HOSTNAME: 127.0.0.1:27017
  DATABASE: c2c
  USERNAME: erhuo
  PASSWORD: fighting

ENV: local


SA_APP_ID : id
SA_SECRET : seceret
SA_TOKEN  : token

#   DEV
APP_ID: id
APP_SECRET: secret

PUBLIC: public # 目录，储存各种用户上传的文件

MCH_ID: MCH_ID
API_KEY: API_KEY
CERT_PATH: CERT_PATH

LEAN_APPID: LEAN_APPID-gzGzoHsz
LEAN_APPKEY: LEAN_APPKEY
LEAN_MASTERKEY: LEAN_MASTERKEY
