SERVER:
  ADDRESS: 127.0.0.1
  PORT: 8000
  URL_PREFIX: http://localhost:8000 # 地址前缀，不以/结尾
  SECRET_KEYS: 'this is secret key' # 加密session用的key
  MAXAGE: 0 # 静态资源缓存时间,单位ms,推荐在正式服务器上启用

MONGODB: # mongodb配置
  HOSTNAME: 39.106.112.28:27017
  DATABASE: c2c

ENV: local

#   OL
APP_ID: wxeb3470bf6817d8b1
APP_SECRET: fb90ff46df72a1c84f432fd2bcc941d3

SA_APP_ID : wxbe500a2cde70261c
SA_SECRET : 0b9b5299cb18bee3ad62ab5fa5ecc4d9
SA_TOKEN  : mengmengdaerhuotu

#   DEV
#   APP_ID: wxeedf8d0cba505192
#   APP_SECRET: 599fb18cb0bb8c712353031a37d8e58c
PUBLIC: public # 目录，储存各种用户上传的文件